### PR TITLE
Fix: downgrade rdkit to the version 2020.09.1

### LINKED ISSUE #147: The image is built with tornado==6.1
Currently the container is erroneously built with `tornado==6.1` albeit only being compatible with `tornado<5`. **This affects all recent images.**

To reproduce, for example with the recently tagged release (`v20.11.0`):
```
git checkout v20.11.0
docker build . -t aiidalab-docker-stack:v20.11.0 --no-cache  # --no-cache is important!!
docker run --name=aiidalab aiidalab-docker-stack:v20.11.0
```
Then enter the container with
```
$ docker exec -it aiidalab /bin/bash
# su aiida
$ pip list --format=freeze | grep tornado
tornado==6.1
```

This is a **critical issue**, because it affects all images (even older ones) and renders the image unusable for submissions, e.g., with the QE app.

### PR DESCRIPTION
**Pull request by yakutovicha**
fixes #147

The version 2020.09.2 introduces a dependency on tornado6

### CODE REVIEW

**Comment by csadorf** [comment]
> The version 2020.09.2 introduces a dependency on tornado6

I tried to verify that, but couldn't find anything. Can you add a link to the changelog entry or similar?

**Comment by yakutovicha** [comment]
> > The version 2020.09.2 introduces a dependency on tornado6
> 
> I tried to verify that, but couldn't find anything. Can you add a link to the changelog entry or similar?

I didn't check it myself, I can only cite you: https://github.com/aiidalab/aiidalab-docker-stack/issues/147#issuecomment-735252558

**Review by csadorf — APPROVED** [review]
Ok, please let's not upgrade this again. 😆

**Comment by yakutovicha** [comment]
> Ok, please let's not upgrade this again. 😆

I will try :)

**Pull request merged**
