### PR TITLE
Install and enable ipywidgets-extended.

### PR DESCRIPTION
**Pull request by csadorf**
Resolves https://github.com/CasperWA/voila-optimade-client/issues/235 .

### CODE REVIEW

**Review by CasperWA — APPROVED** [review]
_This_ is what I needed :)

The long-term solution here, would be for me to contribute this widget back to `ipywidgets` and then this can be removed again?

**Comment by csadorf** [comment]
> _This_ is what I needed :)
> 
> The long-term solution here, would be for me to contribute this widget back to `ipywidgets` and then this can be removed again?

Yes, and we should also think about implementing a more systematic way to install and enable required Jupyter extensions.

**Comment by CasperWA** [comment]
@yakutovicha I think we're waiting on your approval and merging here :)

**Review by yakutovicha — APPROVED** [review]
approved :)

**Pull request merged**
