### PR TITLE
Use docker buildx bake as build system.

### PR DESCRIPTION
**Pull request by csadorf**
Switch to [docker buildx bake](https://docs.docker.com/engine/reference/commandline/buildx_bake/) as build system.

### CODE REVIEW

**Review by yakutovicha — COMMENTED** [review]
When I tried to build this in a dedicated conda environment, I got the following error:
```bash
(aiidalab-docker-stack) aliaksandrs-mbp:aiidalab-docker-stack yakutovicha$ doit build
.  build
docker-bake.hcl:49
--------------------
  47 |     target "lab" {
  48 |       context = "stack/lab"
  49 | >>>   contexts = {
  50 |         base = "target:base"
  51 |       }
--------------------
error: docker-bake.hcl:49,3-11: Unsupported argument; An argument named "contexts" is not expected here.
TaskFailed - taskid:build
Command failed: 'docker buildx bake' returned 1
```

Does it mean my docker is outdated, or is there something else that could cause this?

**Comment by csadorf** [comment]
> Does it mean my docker is outdated, or is there something else that could cause this?

I assume it might be a version issue, here are mine:
```
$ docker --version
Docker version 20.10.17, build 100c701
$ docker buildx version
github.com/docker/buildx v0.8.2-docker 6224def4dd2c3d347eee19db595348c50d7cb491
```
Can you check yours?

**Comment by yakutovicha** [comment]
> > Does it mean my docker is outdated, or is there something else that could cause this?
> 
> I assume it might be a version issue, here are mine:
> 
> ```
> $ docker --version
> Docker version 20.10.17, build 100c701
> $ docker buildx version
> github.com/docker/buildx v0.8.2-docker 6224def4dd2c3d347eee19db595348c50d7cb491
> ```
> 
> Can you check yours?

Yep, it is outdated, I will now try to update and check it again.

```bash
$ docker --version
Docker version 20.10.11, build dea9396
$ docker buildx version
github.com/docker/buildx v0.7.1 05846896d149da05f3d6fd1e7770da187b52a247
```

**Comment by yakutovicha** [comment]
Ok, after the update things are working again. Maybe we should write down that users should have at least version 0.8.2 of docker buildx.

**Review by yakutovicha — APPROVED** [review]
Tested locally, all good. Thanks, @csadorf.

As I suggested earlier, please add one line to the readme mentioning that the version of `docker buildx` should be at least 0.8.2

**Comment by csadorf** [comment]
> As I suggested earlier, please add one line to the readme mentioning that the version of `docker buildx` should be at least 0.8.2

Sure, but it should be 0.7.1, right? Because that's the version I successfully ran this with.

**Comment by yakutovicha** [comment]
> > As I suggested earlier, please add one line to the readme mentioning that the version of `docker buildx` should be at least 0.8.2
> 
> Sure, but it should be 0.7.1, right? Because that's the version I successfully ran this with.

wait, I am confused.

I guess your version is:
```
$ docker --version
Docker version 20.10.17, build 100c701
$ docker buildx version
github.com/docker/buildx v0.8.2-docker 6224def4dd2c3d347eee19db595348c50d7cb491
```
so `v0.8.2`. I had `v0.7.1` and it did not work.

**Pull request merged**
