### PR TITLE
Bump aiida-core to 2.4.3 to include the fix of mpi setup

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by unkcpz** [comment]
Need to wait for aiida-core docker stack is available. This is one small reason I don't like using conda to install the core dependencies, with pypi we can always get things immediately.

**Comment by danielhollas** [comment]
> Need to wait for aiida-core docker stack is available. This is one small reason I don't like using conda to install the core dependencies, with pypi we can always get things immediately.

True, but the couple days wait is not worth it IMHO. Also, installing via pip would most likely increase the image size since conda is more efficient for bundling non-Python dependencies.

**Comment by unkcpz** [comment]
> True, but the couple days wait is not worth it IMHO. 

Okay, not hard to have conda feedstock update manually. Let's keep on using conda, we live quite well with it.

**Review by danielhollas — APPROVED** [review]
@yakutovicha can you please test that this fixes your MPI issues?
(image `aiidalab/full-stack:pr-427`)

**Comment by unkcpz** [comment]
Discussed with @yakutovicha on slack, we agree on get this merged and ask @cpignedoli test on the new image.

**Pull request merged**
