### PR TITLE
check env file exist

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by unkcpz** [comment]
Well, I think the more proper behaviour is there is an empty `.env` file in the repository.

**Review by csadorf — CHANGES_REQUESTED** [review]
What issue is addressed by this PR? Generally I would not think that it should be a requirement that the `.env` file exists when first running the script, since the `configure` command is there to create the file.

**Comment by unkcpz** [comment]
I guess sometimes we may want to just start the container with all default settings or the first time before running `configuration` I want to know what is being set default. Instead of a file exist check, maybe just put a default `.env` is better?

**Comment by yakutovicha** [comment]
I assume due to the invention of [aiidalab-launch](https://github.com/aiidalab/aiidalab-launch) we can close this PR, right?

**Comment by unkcpz** [comment]
@yakutovicha Yes, thanks!

**Pull request closed without merging**
