### PR TITLE
Implement pre-installed QE components for demo server

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by superstar54** [comment]
I tested using `aiidalab-launch`. This is the profile config:
```
port = 8909
default_apps = []
system_user = "jovyan"
image = "ghcr.io/aiidalab/qe:sha-c222d42"
home_mount = "aiidalab_qe-image_home"
extra_mounts = []
```

QE app related things are all installed. Good!

But when I run a calculation for `Si`.  The job failed with `Finished [322] The XML output file has an unsupported format.`

Screenshot from 2023-07-20 12-25-12


Screenshot from 2023-07-20 12-17-07

I check the remote folder, and the `aiida.in` and `aiida.out` are correct and the job was finished successfully. I don't know why the process failed.

**Comment by unkcpz** [comment]
I thought `aiida-quantumespresso` start to support QE-7.2 but seems not https://github.com/aiidateam/aiida-quantumespresso#compatibility-matrix?? 
@mbercx, any idea where the compatibility comes from? 
I think I made a mistake to pin `aiida-quantumespresso` to `~=4.2.0` is https://github.com/aiidalab/aiidalab-qe/blob/v23.04.5/setup.cfg by https://github.com/aiidalab/aiidalab-qe/pull/430

**Comment by unkcpz** [comment]
Hi @superstar54 can you try this again? I test it locally and it is all good now, the problem as I expected is the version of aiida-quantumespresso `4.2.0` not compatible with qe-7.2.

**Comment by unkcpz** [comment]
@superstar54 I merge the PR since I am going to work on doc and prepare the Quantum Mobile by Thursday. The release to the dockerhub looks all fine. If you still want to have a test you can try the image with `docker pull aiidalab/qe:edge`.

**Comment by superstar54** [comment]
@unkcpz Thanks for the work. 
Two comments:
- there is an unwanted `aiidalab-qe` folder in the home directory, as shown below. It seems you install the qeapp twice, one by `aiidalab`, another by `pip`. Please check.
```
(base) jovyan@ca4f41965229:~$ ls
aiidalab-qe  apps  work
```
- when using the qeapp the first time, I still need to wait a long time (~ 3min) for the setup (e.g. pseudo). This is not good in a demo. Is it possible to have all the setups in the image?

**Pull request merged**
