### PR TITLE
Bump actions/artifact-upload to v4

### PR DESCRIPTION
**Pull request by unkcpz**
This is a revert amendment of https://github.com/aiidalab/aiidalab-docker-stack/pull/419 which merged improperly with test commints.

- The changes should significantly speed up artifact upload, see https://github.com/actions/upload-artifact#v4---whats-new
- Also include the updates of `action/checkout` action to v4
- include fix the python version of running environment to `3.11`.
- include the changes of removing paths change detection in `docker.yml`

### CODE REVIEW

**Comment by unkcpz** [comment]
I am ordering a request for the firewall rule in PSI, hope it will work. I'll keep this PR open for the test. 
Will also look into the timeout of the action.

**Comment by danielhollas** [comment]
Thanks @unkcpz. If the firewall rule does not fix it, we can use V3 action for arm and v4 for amd, and then focus on removing the artifacts entirely.

**Comment by unkcpz** [comment]
> If the firewall rule does not fix it, we can use V3 action for arm and v4 for amd, and then focus on removing the artifacts entirely.

Sadly no, from IT he said the TCP ports 80/443 is allowed by default, therefore no specific firewall rule is needed.

**Comment by unkcpz** [comment]
I test it with aiida-core image which is a smaller one, all good. I think it is the problem of the action it self. See https://github.com/aiidateam/aiida-core/pull/6228

**Comment by unkcpz** [comment]
I remove the compression setting and all works. There are two possibilities, 1) the artifact is too large 2) no compression causes the problem.

**Comment by unkcpz** [comment]
> then focus on removing the artifacts entirely.

I'll find time work on this this week anyway.

**Review by danielhollas — APPROVED** [review]

**Pull request merged**
