### PR TITLE
Update aiidalab to version 21.11.0

### PR DESCRIPTION
**Pull request by csadorf**

### CODE REVIEW

**Comment by yakutovicha** [comment]
I tried to run the thing locally, and it appears to me that the issue is with the `aiidalab` package:

```python
+ aiidalab install --yes aiidalab-widgets-base~=1.0

Collecting apps matching requirements... Traceback (most recent call last):
  File "/opt/conda/bin/aiidalab", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/__main__.py", line 408, in install
    for requirement in map(_parse_requirement, set(app_requirement))
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/__main__.py", line 408, in <dictcomp>
    for requirement in map(_parse_requirement, set(app_requirement))
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/__main__.py", line 295, in _find_version_to_install
    app = _find_registered_app_from_id(app_requirement.name)
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/__main__.py", line 199, in _find_registered_app_from_id
    app = AiidaLabApp.from_id(name)
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/app.py", line 114, in from_id
    local_registry_entry = cls._registry_entry_from_path(app_path)
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/app.py", line 95, in _registry_entry_from_path
    "metadata": asdict(Metadata.parse(path)),
  File "/opt/conda/lib/python3.7/site-packages/aiidalab/metadata.py", line 113, in parse
    raise ValueError(f"Directory '{root}' does not exist.")
ValueError: Directory '/home/aiida/apps/aiidalab-widgets-base' does not exist.
*** /etc/my_init.d/80_prepare-aiidalab.sh failed with status 1
```

Apparently, aiidalab could not install the awb package.

**Comment by csadorf** [comment]
> Apparently, aiidalab could not install the awb package.

Working on it.

**Comment by csadorf** [comment]
The issue should be resolved in [aiidalab version 21.11.0](https://github.com/aiidalab/aiidalab/pull/243). We should update this PR once that version is released.

**Review by yakutovicha — APPROVED** [review]
well, I am happy with the changes :)

**Pull request merged**
