### PR TITLE
CI: always display the container log (before and after container restart).

### PR DESCRIPTION
**Pull request by yakutovicha**
This functionality is needed to be able to inspect the container log in case of any issues.

### CODE REVIEW

**Comment by yakutovicha** [comment]
@csadorf can you please have a look at what is wrong with the CI?

I have no idea why the part
https://github.com/aiidalab/aiidalab-docker-stack/blob/5162d179f88a2ee9c7a786fbba8348e0452fba92/.github/workflows/build_and_test_on_pr.yml#L31-L40
is working fine, while the part 
https://github.com/aiidalab/aiidalab-docker-stack/blob/5162d179f88a2ee9c7a786fbba8348e0452fba92/.github/workflows/build_and_test_on_pr.yml#L77-L80

cannot display the variable's value. I am really at a loss here.

**Comment by csadorf** [comment]
@yakutovicha Based on the output in https://github.com/aiidalab/aiidalab-docker-stack/runs/4072518493?check_suite_focus=true, line https://github.com/aiidalab/aiidalab-docker-stack/blob/5162d179f88a2ee9c7a786fbba8348e0452fba92/.github/workflows/build_and_test_on_pr.yml#L80 runs just fine, but line https://github.com/aiidalab/aiidalab-docker-stack/blob/5162d179f88a2ee9c7a786fbba8348e0452fba92/.github/workflows/build_and_test_on_pr.yml#L84 fails.

That's because the `test_run` step fails and therefore never reaches: https://github.com/aiidalab/aiidalab-docker-stack/blob/5162d179f88a2ee9c7a786fbba8348e0452fba92/.github/workflows/build_and_test_on_pr.yml#L74

**Comment by yakutovicha** [comment]
@csadorf thanks for looking into this, everything is clear now.

**Comment by csadorf** [comment]
@yakutovicha Could you provide some brief motivation for this as part of the PR description, please?

**Comment by yakutovicha** [comment]
> @yakutovicha Could you provide some brief motivation for this as part of the PR description, please?

done

**Review by csadorf — CHANGES_REQUESTED** [review]
Overall fine, I'd just suggest to rename the variables:
`docker_id_before` -> `docker_id_first_run`
`docker_id_after` -> `docker_id_second_run`
I think that is a bit more obvious then `before_(restart)` and `after_(restart)`.

**Comment by yakutovicha** [comment]
Provided that I made the requested modifications, I am going to merge the PR.

**Pull request merged**
