### PR TITLE
Downgrade artifact-upload to fix arm64 build?

### PR DESCRIPTION
**Pull request by danielhollas**
The arm64 build is failing on artifact-upload step. I am not sure if that is the consequence of the bump of `actions/artifact-upload` to v4, or something is wrong with our self-hosted runners. Let's see if downgrading helps.

### CODE REVIEW

**Comment by danielhollas** [comment]
Looks like we will have to downgrade the `actions/upload-artifact` back to v3 since the v4 does not work on our self-hosted runner yet.

In the [release notes](https://github.com/actions/upload-artifact#breaking-changes), they mention this:
> On self hosted runners, additional [firewall rules](https://github.com/actions/toolkit/tree/main/packages/artifact#breaking-changes) may be required.

cc @mbercx @unkcpz 

Before this is debugged, I'd suggest to merge this to get us working again.

**Comment by unkcpz** [comment]
Thanks for taking care of `artifact-upload` action. If it break the github workflow, we have to postpone the update of it. 
And I'll work on not uploading the artifact this week.

**Review by unkcpz — APPROVED** [review]

**Comment by unkcpz** [comment]
One more thing that needs to be noticed is running on @mbercx's machine may not the final solution, since he found somehow it maybe the reason that caused his daily AiiDA work environment break.

**Comment by danielhollas** [comment]
Closed in favour of #423

**Pull request closed without merging**
