### PR TITLE
Enable the custom widgets with Voila

### PR DESCRIPTION
**Pull request by dou-du**
This will allow to show custom widgets with Voila, for instance the widget periodic table.

### CODE REVIEW

**Comment by dou-du** [comment]
> Thanks, @dou-du, I have one question and one suggestion.
> 
> q: did you try to run it yourself? The periodic table stopped working for me, even with the app mode.
> s: Can you please add it for the JupyterHub part as well?

I cannot run it either. I need to run two additional command lines:

```bash
jupyter nbextension install --py --user widget_periodictable
jupyter nbextension enable widget_periodictable --user --py
```
I just update it in the Dockerfile and make the pull request here. I am not sure about whether it will fix the problem. Could you recompile the docker image and test it ? Thanks.

**Comment by yakutovicha** [comment]
I tested it locally, but it didn't work. Please try to fix the problems. Here are the commands to test things locally

```shell
PORT=8888  # Local port
IMAGE='aiidalab-docker-stack:develop'  # image name
FOLDER="${HOME}/aiidalab"  # Folder to be mounted
docker build -t ${IMAGE} ./  # To build the container
CONTAINERID=`docker run -d -p ${PORT}:8888 -e JUPYTER_TOKEN=${TOKEN} -v "${FOLDER}":/home/aiida ${IMAGE}`  #To start the container
docker exec --tty ${CONTAINERID} wait-for-services  # To wait until the container is started
```

**Comment by yakutovicha** [comment]
@dou-du, it should be working now. Do you want to have a look?

**Comment by dou-du** [comment]
> @dou-du, it should be working now. Do you want to have a look?

Thanks a lot. I will check it later today.

**Pull request merged**
